/**
 * BlaBlaCar APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This step requires the client to redirect the user to the phone number certification flow. The client should then resume the booking flow by validating this step with the backend.
 */
export interface PhoneCertifyStep { 
    version: number;
    name: PhoneCertifyStep.NameEnum;
}
export namespace PhoneCertifyStep {
    export type NameEnum = 'PHONE_CERTIFY';
    export const NameEnum = {
        CERTIFY: 'PHONE_CERTIFY' as NameEnum
    };
}