//
// BookingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BookingResponse: Codable { 


    public var steps: [AnyOfLoginStepPhoneCertifyStep]?
    /** This flow identifier is generated by the client application and embedded in the first request to Edge. It will be then added in each subsequent requests and responses of the booking flow. */
    public var flowId: UUID?

    public init(steps: [AnyOfLoginStepPhoneCertifyStep]?, flowId: UUID?) {
        self.steps = steps
        self.flowId = flowId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case steps
        case flowId = "flow_id"
    }

}
