//
// LoginStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This step requires the client to redirect the user to the login flow. After a successful login, the client should resume the booking flow by validating this step with the backend. */
public struct LoginStep: Codable { 


    public enum Name: String, Codable, CaseIterable {
        case login = "LOGIN"
    }
    public var context: LoginStepContext
    public var name: Name

    public init(context: LoginStepContext, name: Name) {
        self.context = context
        self.name = name
    }

}
