//
// PhoneCertifyStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This step requires the client to redirect the user to the phone number certification flow. The client should then resume the booking flow by validating this step with the backend. */
public struct PhoneCertifyStep: Codable { 


    public enum Name: String, Codable, CaseIterable {
        case phoneCertify = "PHONE_CERTIFY"
    }
    public var version: Double
    public var name: Name

    public init(version: Double, name: Name) {
        self.version = version
        self.name = name
    }

}
