//
// LoginContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LoginContext: Codable { 


    public var p1: String
    public var p2: Int

    public init(p1: String, p2: Int) {
        self.p1 = p1
        self.p2 = p2
    }

}
