//
// Login.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This step requires the client to redirect the user to the login flow. After a successful login, the client should resume the booking flow by validating this step with the backend. */
public struct Login: Codable { 


    public var context: LoginContext

    public init(context: LoginContext) {
        self.context = context
    }

}
