//
// LoginStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LoginStep: Codable { 


    public var name: String
    public var context: LoginContext

    public init(name: String, context: LoginContext) {
        self.name = name
        self.context = context
    }

}
