//
// PhoneCertify.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This step requires the client to redirect the user to the phone number certification flow. The client should then resume the booking flow by validating this step with the backend. */
public struct PhoneCertify: Codable { 


    public var version: Double

    public init(version: Double) {
        self.version = version
    }

}
