//
// PhoneCertifyStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PhoneCertifyStep: Codable { 


    public var name: String
    public var version: Double

    public init(name: String, version: Double) {
        self.name = name
        self.version = version
    }

}
