/*
 * BlaBlaCar APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LoginStepContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-29T13:47:20.209+02:00[Europe/Paris]")
public class LoginStepContext {
  @SerializedName("p1")
  private String p1 = null;

  @SerializedName("p2")
  private Integer p2 = null;

  public LoginStepContext p1(String p1) {
    this.p1 = p1;
    return this;
  }

   /**
   * Get p1
   * @return p1
  **/
  @Schema(required = true, description = "")
  public String getP1() {
    return p1;
  }

  public void setP1(String p1) {
    this.p1 = p1;
  }

  public LoginStepContext p2(Integer p2) {
    this.p2 = p2;
    return this;
  }

   /**
   * Get p2
   * @return p2
  **/
  @Schema(required = true, description = "")
  public Integer getP2() {
    return p2;
  }

  public void setP2(Integer p2) {
    this.p2 = p2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginStepContext loginStepContext = (LoginStepContext) o;
    return Objects.equals(this.p1, loginStepContext.p1) &&
        Objects.equals(this.p2, loginStepContext.p2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(p1, p2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginStepContext {\n");
    
    sb.append("    p1: ").append(toIndentedString(p1)).append("\n");
    sb.append("    p2: ").append(toIndentedString(p2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
