/**
 * BlaBlaCar APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Step } from './step';


export interface BookingResponse { 
    steps?: Array<Step>;
    /**
     * This flow identifier is generated by the client application and embedded in the first request to Edge. It will be then added in each subsequent requests and responses of the booking flow.
     */
    flow_id?: string;
}

