/**
 * BlaBlaCar APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginContext } from './loginContext';


/**
 * This step requires the client to redirect the user to the login flow. After a successful login, the client should resume the booking flow by validating this step with the backend.
 */
export interface Login { 
    context: LoginContext;
}

