/**
* BlaBlaCar APIs
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: squad-edge@blablacar.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param p1 
 * @param p2 
 */

data class LoginContext (
    @Json(name = "p1")
    val p1: kotlin.String,
    @Json(name = "p2")
    val p2: kotlin.Int
)

