/**
* BlaBlaCar APIs
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: squad-edge@blablacar.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * This step requires the client to redirect the user to the phone number certification flow. The client should then resume the booking flow by validating this step with the backend.
 * @param version 
 */

data class PhoneCertify (
    @Json(name = "version")
    val version: java.math.BigDecimal
)

