/**
* BlaBlaCar APIs
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: squad-edge@blablacar.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.PhoneCertify
import org.openapitools.client.models.Step

import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param version 
 */

data class PhoneCertifyStep (
    @Json(name = "name")
    override val name: kotlin.String,
    @Json(name = "version")
    val version: java.math.BigDecimal
) : Step

