//
// LoginStepContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginStepContext: Codable {

    public var p1: String
    public var p2: Int

    public init(p1: String, p2: Int) {
        self.p1 = p1
        self.p2 = p2
    }


}

