/**
 * BlaBlaCar APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.LoginStepContext

/**
 * This step requires the client to redirect the user to the login flow. After a successful login, the client should resume the booking flow by validating this step with the backend.
 * @param context 
 * @param name 
 */
data class LoginStep (
    val context: LoginStepContext,
    val name: LoginStep.Name

) {
    /**
    * 
    * Values: lOGIN
    */
    enum class Name(val value: kotlin.String){
        lOGIN("LOGIN");
    }
}