/**
 * BlaBlaCar APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * This step requires the client to redirect the user to the phone number certification flow. The client should then resume the booking flow by validating this step with the backend.
 * @param version 
 * @param name 
 */
data class PhoneCertifyStep (
    val version: java.math.BigDecimal,
    val name: PhoneCertifyStep.Name

) {
    /**
    * 
    * Values: cERTIFY
    */
    enum class Name(val value: kotlin.String){
        cERTIFY("PHONE_CERTIFY");
    }
}