/**
 * BlaBlaCar APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: squad-edge@blablacar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Step } from './step';

export interface BookingResponse { 
    steps?: Array<Step>;
    /**
     * This flow identifier is generated by the client application and embedded in the first request to Edge. It will be then added in each subsequent requests and responses of the booking flow.
     */
    flowId?: string;
}