//
// LoginStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginStep: Codable {

    public var name: String
    public var context: LoginStepContext

    public init(name: String, context: LoginStepContext) {
        self.name = name
        self.context = context
    }


}

