//
// PhoneCertifyStep.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PhoneCertifyStep: Codable {

    public var name: String
    public var version: BigDecimal

    public init(name: String, version: BigDecimal) {
        self.name = name
        self.version = version
    }


}

